spring:
  profiles: dev
server:
  port: 7000
---
spring:
  profiles: qa
server:
  port: 7001
---
spring:
  profiles:
    active: dev
---
management:
  security:
    enabled: false
---
logging:
  level:
    org.springframework.web: ERROR
    com.aa: DEBUG
email: onlyankur@gmail.com
thread-pool: 10
---
management:
  endpoints:
    web:
      exposure:
        include: "*"
---
management:
  endpoint:
    health:
      show-details: "ALWAYS"
---
#Eureka Server configuration
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9006/eureka
    instance:
    preferIpAddress: true
spring:
  application:
    name: ankur_eureka_client

